# -*- coding: utf-8 -*-
"""Homework 1st.

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CFKV_1Zv6m_iYh6k9EthdClq6GYVjne3

### eg 1.
"""

def compute(a,b,c):
    q=b**2-4*a*c

    if  q<0:
        output="Your equation has no root."
    elif q==0:
        output=-b/2*a
    else:
        q1=(-b+q**0.5)/(2*a)
        q2=(-b-q**0.5)/(2*a)
        output='{}, {}'.format(q1, q2)
    return output


a=eval(input())
b=eval(input())
c=eval(input())
print(compute(a,b,c))

"""### eg 2.

"""

row = "{:^10}{:^10}{:^10}{:^10}{:^10}{:^10}{:^10}{:^10}{:^10}"
print(row.format("P","Q", "P∧Q","P∨Q","~(P∧Q)","~(P∨Q)","P→Q","P←Q","P↔Q"))
print(row.format("F","F","F","F","F","F","T","T","T"))
print(row.format("F","T","F","T","T","T","T","F","F"))
print(row.format("T","F","F","T","T","T","F","T","F"))
print(row.format("T","T","T","T","F","F","T","T","T"))